import assert from 'node:assert/strict';
import fs from 'node:fs';
import {battlePath,distance} from '../web/demos/jiangnan-hd2d/src/rules.mjs';
const port=Number(process.argv[2]||9225),out=process.env.HD2D_EVIDENCE_DIR||'/tmp/wudao-hd2d-evidence';fs.mkdirSync(out,{recursive:true});
const tabs=await(await fetch(`http://127.0.0.1:${port}/json`)).json();const tab=tabs.find(t=>t.type==='page'&&/^https?:/.test(t.url));if(!tab)throw Error('No HTTP browser page available');const origin=new URL(tab.url).origin;const ws=new WebSocket(tab.webSocketDebuggerUrl);await new Promise(r=>ws.addEventListener('open',r,{once:true}));let id=0;const pending=new Map(),errors=[];
ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.exception?.description);if(m.method==='Runtime.consoleAPICalled'&&m.params.type==='error')errors.push(m.params.args.map(a=>a.value||a.description).join(' '));if(m.method==='Log.entryAdded'&&m.params.entry.level==='error')errors.push(m.params.entry.text+' '+m.params.entry.url);if(pending.has(m.id)){pending.get(m.id)(m.result);pending.delete(m.id);}};
const send=(method,params={})=>new Promise(r=>{const n=++id;pending.set(n,r);ws.send(JSON.stringify({id:n,method,params}));});
const evaluate=async expression=>{const r=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description);return r.result.value;};
const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function until(expression,timeout=240000){const start=Date.now();while(Date.now()-start<timeout){if(await evaluate(expression))return;await delay(250);}throw Error('Timed out: '+expression+'\n'+JSON.stringify(await evaluate('window.__jiangnan?.snapshot()')));}
async function click(action,value){await evaluate(`(()=>{const b=document.querySelector(${JSON.stringify(`[data-action="${action}"]${value===undefined?'':`[data-value="${value}"]`}`)});if(!b)throw Error('Missing ${action}');b.click();})()`);await delay(120);}
async function go(id){console.log('Travel:',id);assert.equal(await evaluate(`window.__jiangnan.go(${JSON.stringify(id)})`),true);if(id==='innDoor'||id==='innExit')await until(`window.__jiangnan.snapshot().scene===${JSON.stringify(id==='innDoor'?'inn':'town')}`);else await until(`!document.querySelector('#overlay').hidden`);}
async function screenshot(name){console.log('Capture:',name);const shot=await send('Page.captureScreenshot',{format:'png'});fs.writeFileSync(`${out}/${name}.png`,Buffer.from(shot.data,'base64'));}
await send('Runtime.enable');await send('Log.enable');await send('Log.clear');errors.length=0;await send('Page.enable');
await send('Emulation.setDeviceMetricsOverride',{width:1280,height:720,deviceScaleFactor:1,mobile:false});
await send('Page.navigate',{url:`${origin}/demos/jiangnan-hd2d/?debug=1${process.env.HD2D_FAST?'&quality=low':''}`});await until('!!window.__jiangnan');
await click('settings');await click('resetAsk');await click('reset');await delay(1500);await screenshot('01-town-day');
await click('settings');await click('light');await click('close');await delay(1200);await screenshot('02-town-evening');await click('settings');await click('light');if((await evaluate('__jiangnan.snapshot()')).settings.quality!=='low')await click('quality');await click('close');
await send('Emulation.setDeviceMetricsOverride',{width:844,height:390,deviceScaleFactor:1,mobile:false});await delay(800);await screenshot('03-mobile-landscape');assert.ok(await evaluate('document.documentElement.scrollWidth<=innerWidth'));
await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await delay(800);await screenshot('04-mobile-portrait');assert.ok(await evaluate('document.documentElement.scrollWidth<=innerWidth'));
await send('Emulation.setDeviceMetricsOverride',{width:800,height:450,deviceScaleFactor:1,mobile:false});
await go('tea');const stopped=await evaluate('__jiangnan.snapshot().position');await send('Input.dispatchKeyEvent',{type:'keyDown',key:'w',code:'KeyW'});await delay(400);await send('Input.dispatchKeyEvent',{type:'keyUp',key:'w',code:'KeyW'});assert.deepEqual(await evaluate('__jiangnan.snapshot().position'),stopped);await click('accept');assert.equal((await evaluate('__jiangnan.snapshot()')).quest,1);
await go('rope');await click('close');await go('tag');await click('close');assert.equal((await evaluate('__jiangnan.snapshot()')).quest,2);
await go('innDoor');await delay(600);await screenshot('05-inn');await go('keeper');const before=await evaluate('__jiangnan.snapshot()');await click('buy');const after=await evaluate('__jiangnan.snapshot()');assert.equal(after.coins,before.coins-12);assert.equal(after.medicine,before.medicine+1);await click('close');
await go('escort');await click('confirm');await go('innExit');await go('guard');await click('fight');await delay(600);await screenshot('06-battle');
for(let turn=0;turn<35;turn++){
 const s=await evaluate('__jiangnan.snapshot()');if(!s.battle)break;console.log('Battle:',turn,s.battle.hero.hp);const b=s.battle,h=b.hero,e=b.enemies.filter(e=>e.hp>0).sort((a,c)=>distance(h,a)-distance(h,c))[0];
 if(distance(h,e)>1&&!b.moved){const cells=[];for(let x=0;x<8;x++)for(let z=0;z<6;z++)if(battlePath(b,{x,z}).length)cells.push({x,z});cells.sort((a,c)=>distance(a,e)-distance(c,e));if(cells.length){const p=await evaluate(`__jiangnan.screenCell(${cells[0].x},${cells[0].z})`);await send('Input.dispatchMouseEvent',{type:'mousePressed',x:p.x,y:p.y,button:'left',clickCount:1});await send('Input.dispatchMouseEvent',{type:'mouseReleased',x:p.x,y:p.y,button:'left',clickCount:1});await delay(500);}}
 const n=await evaluate('__jiangnan.snapshot()'),d=distance(n.battle.hero,e);const action=n.hp<45&&n.medicine?'medicine':d<=2&&n.mp>=12?'skill':d<=1?'attack':'defend';await click('selectSkill',action);await click('selectEnemy',e.id);await click('strike');await delay(1100);
}
assert.equal((await evaluate('__jiangnan.snapshot()')).quest,5);await go('chest');await click('close');await go('innDoor');await go('escort');await click('deliver','decline');const completed=await evaluate('__jiangnan.snapshot()');assert.equal(completed.quest,7);assert.equal(completed.reputation,3);await screenshot('07-completed');await go('escort');await click('close');assert.equal((await evaluate('__jiangnan.snapshot()')).coins,completed.coins);
const journeyStats=await evaluate('__jiangnan.stats()');await send('Page.reload');await until('!!window.__jiangnan');assert.equal((await evaluate('__jiangnan.snapshot()')).quest,7);
const stats=await evaluate('__jiangnan.stats()');const report={quest:7,coins:completed.coins,reputation:completed.reputation,errors,stats:journeyStats,reloadStats:stats,environment:'Headless Chrome, SwiftShader software rendering; not a hardware FPS acceptance result'};fs.writeFileSync(`${out}/report.json`,JSON.stringify(report,null,2));assert.deepEqual(errors,[]);console.log(JSON.stringify(report,null,2));ws.close();
